INSERT INTO drink (alcohol_status, date, api_id, name, image, recipe) VALUES ('Alcoholic', '2017-09-02 11:36:19', '17185', 'Casino', 'https:\/\/www.thecocktaildb.com\/images\/media\/drink\/1mvjxg1504348579.jpg','Pour all ingredients into shaker with ice cubes. Shake well. Strain into chilled cocktail glass. Garnish with a lemon twist and a maraschino cherry. Serve without a straw.');
INSERT INTO drink (alcohol_status, date, api_id, name, image, recipe) VALUES ('Ordinary Drink', '2016-07-21 09:42:01', '11202', 'Caipirinha','https:\/\/www.thecocktaildb.com\/images\/media\/drink\/jgvn7p1582484435.jpg','Place lime and sugar into old fashioned glass and muddle (mash the two ingredients together using a muddler or a wooden spoon). Fill the glass with ice and add the Cacha\u00e7a.');
INSERT INTO drink (alcohol_status, date, api_id, name, image, recipe) VALUES ('Ordinary Drink', '2016-07-21 09:42:01', '666', 'DRINKKK','https:\/\/www.thecocktaildb.com\/images\/media\/drink\/jgvn7p1582484435.jpg','Place lime and sugar into old fashioned glass and muddle (mash the two ingredients together using a muddler or a wooden spoon). Fill the glass with ice and add the Cacha\u00e7a.');
INSERT INTO drink (api_id, name, alcohol_status, recipe, image, date) VALUES ('17185', 'Casino', 'Alcoholic','Pour all ingredients into shaker with ice cubes. Shake well. Strain into chilled cocktail glass. Garnish with a lemon twist and a maraschino cherry. Serve without a straw.','https://www.thecocktaildb.com/images/media/drink/1mvjxg1504348579.jpg', '2017-09-02 11:36:19');
INSERT INTO drink (api_id, name, alcohol_status, recipe, image, date) VALUES ('11202', 'Caipirinha', 'Alcoholic','Place lime and sugar into old fashioned glass and muddle (mash the two ingredients together using a muddler or a wooden spoon). Fill the glass with ice and add the Cachaça.','https://www.thecocktaildb.com/images/media/drink/jgvn7p1582484435.jpg', '2016-07-21 09:42:01');
INSERT INTO drink (api_id, name, alcohol_status, recipe, image, date) VALUES ('11239', 'Cherry Rum', 'Alcoholic', 'Shake all ingredients with ice, strain into a cocktail glass, and serve.','https://www.thecocktaildb.com/images/media/drink/twsuvr1441554424.jpg', '2015-09-06 16:47:04');
INSERT INTO drink (api_id, name, alcohol_status, recipe, image, date) VALUES ('11288', 'Cuba Libre', 'Alcoholic','Build all ingredients in a Collins glass filled with ice. Garnish with lime wedge.','https://www.thecocktaildb.com/images/media/drink/uuxsrr1473201663.jpg', '2016-09-06 23:41:03');
INSERT INTO drink (api_id, name, alcohol_status, recipe, image, date) VALUES ('13751', 'Cuba Libra', 'Alcoholic','Fill tall glass with ice cubes. Add rum. Rub cut edge of lime on rim of glass then squeeze juice into glass. Fill with Coca-Cola. Garnish with lime slice. Enjoy!','https://www.thecocktaildb.com/images/media/drink/ck6d0p1504388696.jpg', '2017-09-02 22:44:56');
INSERT INTO drink (api_id, name, alcohol_status, recipe, image, date) VALUES ('14181', 'Cafe Savoy', 'Alcoholic', 'Fill mug almost to top with coffee.Add milk, triple sec and brandy. Stir.','https://www.thecocktaildb.com/images/media/drink/vqwptt1441247711.jpg', '2015-09-03 03:35:11');
INSERT INTO drink (api_id, name, alcohol_status, recipe, image, date) VALUES ('14608', 'Cream Soda', 'Alcoholic','Pour 1oz of Spiced Rum into a highball glass with ice. Fill with Ginger Ale.','https://www.thecocktaildb.com/images/media/drink/yqstxr1479209367.jpg', '2016-11-15 11:29:27');
INSERT INTO drink (api_id, name, alcohol_status, recipe, image, date) VALUES ('17830', 'Corn n Oil', 'Alcoholic','Cut the half lime in half again. Add the lime, falernum, and bitters to a rocks glass. Muddle. Add the rum. (Aged Barbados rum such as Plantation 5 Year is recommended). Add ice and stir. Float the blackstrap rum on top. Serve with a straw.','https://www.thecocktaildb.com/images/media/drink/jfvyog1530108909.jpg', '2018-06-27 15:15:09');
INSERT INTO drink (api_id, name, alcohol_status, recipe, image, date) VALUES ('11222', 'Casa Blanca', 'Alcoholic', 'Shake all ingredients with ice, strain into a cocktail glass, and serve.','https://www.thecocktaildb.com/images/media/drink/usspxq1441553762.jpg', '2015-09-06 16:36:02');
INSERT INTO drink (api_id, name, alcohol_status, recipe, image, date) VALUES ('17186', 'Clover Club', 'Alcoholic','Dry shake ingredients to emulsify, add ice, shake and served straight up.','https://www.thecocktaildb.com/images/media/drink/t0aja61504348715.jpg', '2017-09-02 11:38:35');
INSERT INTO drink (api_id, name, alcohol_status, recipe, image, date) VALUES ('17135', 'Citrus Coke', 'Alcoholic','Pour half of coke in a glass. Then add Bacardi and top it off with the remaining coke. Stir and drink up!','https://www.thecocktaildb.com/images/media/drink/uyrvut1479473214.jpg', '2016-11-18 12:46:54');
INSERT INTO drink (api_id, name, alcohol_status, recipe, image, date) VALUES ('11242', 'Chicago Fizz', 'Alcoholic','Shake all ingredients (except carbonated water) with ice and strain into a highball glass over two ice cubes. Fill with carbonated water, stir, and serve.','https://www.thecocktaildb.com/images/media/drink/qwvwqr1441207763.jpg', '2015-09-02 16:29:23');
INSERT INTO drink (api_id, name, alcohol_status, recipe, image, date) VALUES ('11251', 'City Slicker', 'Alcoholic',        'In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a cocktail glass.',        'https://www.thecocktaildb.com/images/media/drink/dazdlg1504366949.jpg', '2017-09-02 16:42:29');
INSERT INTO drink (api_id, name, alcohol_status, recipe, image, date) VALUES ('12800', 'Coffee-Vodka', 'Alcoholic',        'Boil water and sugar until dissolved. Turn off heat. Slowly add dry instant coffee and continue stirring. Add a chopped vanilla bean to the vodka, then combine the cooled sugar syrup and coffee solution with the vodka. Cover tightly and shake vigorously each day for 3 weeks. Strain and filter. Its also best to let the sugar mixture cool completely so the vodka won''t evaporate when its added. If you like a smoother feel to the liqueur you can add about 1 teaspoon of glycerine to the finished product.',        'https://www.thecocktaildb.com/images/media/drink/qvrrvu1472667494.jpg', '2016-08-31 19:18:14');
INSERT INTO drink (api_id, name, alcohol_status, recipe, image, date) VALUES ('13206', 'Caipirissima', 'Alcoholic',        'Same as Caipirinha but instead of cachaca you add WHITE RUM. It''s great!!!!!!!!',        'https://www.thecocktaildb.com/images/media/drink/yd47111503565515.jpg', '2017-08-24 10:05:15');
INSERT INTO drink (api_id, name, alcohol_status, recipe, image, date) VALUES ('16047', 'Campari Beer', 'Alcoholic', 'Use a 15 oz glass. Add Campari first. Fill with beer.',        'https://www.thecocktaildb.com/images/media/drink/xsqrup1441249130.jpg', '2015-09-03 03:58:50');
INSERT INTO drink (api_id, name, alcohol_status, recipe, image, date) VALUES ('17196', 'Cosmopolitan', 'Alcoholic',        'Add all ingredients into cocktail shaker filled with ice. Shake well and double strain into large cocktail glass. Garnish with lime wheel.',        'https://www.thecocktaildb.com/images/media/drink/kpsajh1504368362.jpg', '2017-09-02 17:06:02');
INSERT INTO drink (api_id, name, alcohol_status, recipe, image, date) VALUES ('11224', 'Casino Royale', 'Alcoholic',        'In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a sour glass.',        'https://www.thecocktaildb.com/images/media/drink/3qpv121504366699.jpg', '2017-09-02 16:38:19');
INSERT INTO drink (api_id, name, alcohol_status, recipe, image, date) VALUES ('11255', 'Clove Cocktail', 'Alcoholic',        'Stir all ingredients with ice, strain into a cocktail glass, and serve.',        'https://www.thecocktaildb.com/images/media/drink/qxvtst1461867579.jpg', '2016-04-28 19:19:39');
INSERT INTO drink (api_id, name, alcohol_status, recipe, image, date) VALUES ('12798', 'Coffee Liqueur', 'Alcoholic',        'Combine coffee, sugar and water. Simmer 1 hour and let cool. Add vanilla and vodka. Age in sealed jar 2 to 3 weeks.',        'https://www.thecocktaildb.com/images/media/drink/ryvtsu1441253851.jpg', '2015-09-03 05:17:31');
INSERT INTO drink (api_id, name, alcohol_status, recipe, image, date) VALUES ('13328', 'Chocolate Milk', 'Alcoholic',        'Put the milk in the bottom, pour the Liquer on top and add the dash of amaretto. Do not mix. SLAM IT!',        'https://www.thecocktaildb.com/images/media/drink/j6q35t1504889399.jpg', '2017-09-08 17:49:59');
INSERT INTO drink (api_id, name, alcohol_status, recipe, image, date) VALUES ('17108', 'Coke and Drops', 'Non alcoholic',        'Take a glass, pour the Coke in the glass, then you take 7 drops of lemon juice. Granish with a lemon slice on the rim of the glass.',        'https://www.thecocktaildb.com/images/media/drink/yrtxxp1472719367.jpg', '2016-09-01 09:42:47');
INSERT INTO drink (api_id, name, alcohol_status, recipe, image, date) VALUES ('12734', 'Chocolate Drink', 'Non alcoholic',        'Melt the bar in a small amount of boiling water. Add milk. Cook over low heat, whipping gently (with a whisk, i would assume) until heated well. Don''t let it boil! Serve in coffee mug.',        'https://www.thecocktaildb.com/images/media/drink/q7w4xu1487603180.jpg', '2017-02-20 15:06:20');
INSERT INTO drink (api_id, name, alcohol_status, recipe, image, date) VALUES ('12808', 'Creme de Menthe', 'Alcoholic',        'Bring sugar and water to a boil and simmer for 10 minutes. Cool. Add the remaining ingredients and stir. Cover and let ripen for 1 month.',        'https://www.thecocktaildb.com/images/media/drink/yxswtp1441253918.jpg', '2015-09-03 05:18:38');
INSERT INTO drink (api_id, name, alcohol_status, recipe, image, date) VALUES ('12890', 'Cranberry Punch', 'Non alcoholic',        'Combine first four ingredients. Stir until sugar is dissolved, chill. Then add ginger ale just before serving. Add ice ring to keep punch cold.',        'https://www.thecocktaildb.com/images/media/drink/mzgaqu1504389248.jpg', '2017-09-02 22:54:08');

INSERT INTO measure (quantity) VALUES ('2 oz');
INSERT INTO measure (quantity) VALUES ('1\/4 tsp');
INSERT INTO measure (quantity) VALUES ('1\/4 tsp');
INSERT INTO measure (quantity) VALUES ('2 dashes ');
INSERT INTO measure (quantity) VALUES ('1 ');
INSERT INTO measure (quantity) VALUES ('Juice of 1\/2 ');
INSERT INTO measure (quantity) VALUES ('2 tsp ');
INSERT INTO measure (quantity) VALUES ('Squeeze ');
INSERT INTO measure (quantity) VALUES ('Fill with ');
INSERT INTO measure (quantity) VALUES ('1 oz ');
INSERT INTO measure (quantity) VALUES ('2 oz ');
INSERT INTO measure (quantity) VALUES ('2 oz ');
INSERT INTO measure (quantity) VALUES ('Juice of 1\/2 ');
INSERT INTO measure (quantity) VALUES ('1 part ');



INSERT INTO category (name) VALUES ('Ordinary Drink');
INSERT INTO category (name) VALUES ('Cocktail');
INSERT INTO category (name) VALUES ('Milk \/ Float \/ Shake');
INSERT INTO category (name) VALUES ('Other\/Unknown');
INSERT INTO category (name) VALUES ('Cocoa');
INSERT INTO category (name) VALUES ('Shot');
INSERT INTO category (name) VALUES ('Coffee \/ Tea');
INSERT INTO category (name) VALUES ('Homemade Liqueur');
INSERT INTO category (name) VALUES ('Punch \/ Party Drink');
INSERT INTO category (name) VALUES ('Beer');
INSERT INTO category (name) VALUES ('Soft Drink \/ Soda');

INSERT INTO ingredient (name) VALUES ('Light rum');
INSERT INTO ingredient (name) VALUES ('Applejack');
INSERT INTO ingredient (name) VALUES ('Gin');
INSERT INTO ingredient (name) VALUES ('Dark rum');
INSERT INTO ingredient (name) VALUES ('Sweet Vermouth');
INSERT INTO ingredient (name) VALUES ('Strawberry schnapps');
INSERT INTO ingredient (name) VALUES ('Scotch');
INSERT INTO ingredient (name) VALUES ('Apricot brandy');
INSERT INTO ingredient (name) VALUES ('Triple sec');
INSERT INTO ingredient (name) VALUES ('Southern Comfort');
INSERT INTO ingredient (name) VALUES ('Orange bitters');

INSERT INTO user (name, email) VALUES ('Szymon Skaziński', 'szymon@gmail.com');
INSERT INTO user (name, email) VALUES ('Łukasz Spyra', 'lukasz@gmail.com');
INSERT INTO user (name, email) VALUES ('Kamil Markowski', 'kamil@gmail.com');
INSERT INTO user (name, email) VALUES ('Andrzej Duda', 'duda@gmail.com');
INSERT INTO user (name, email) VALUES ('Anna Maria', 'marysia@gmail.com');
INSERT INTO user (name, email) VALUES ('Adam nowak', 'nowak@gmail.lcom');


UPDATE drink SET category_id =1  WHERE id IN (1,2,3);
UPDATE drink SET category_id =2 WHERE id IN (4,5,6);
UPDATE drink SET category_id =3  WHERE id IN (7,8,9);
UPDATE drink SET category_id =4  WHERE id IN (10,11,12);
UPDATE drink SET category_id =5  where id IN (13,14,15,16,17,18);
UPDATE drink SET category_id =6  where id IN (19,20,21,22,23);
UPDATE drink SET category_id =7  where id = 24;
UPDATE drink SET category_id =8  where id = 25;
UPDATE drink SET category_id =9  where id = 26;
UPDATE drink SET category_id =10  where id = 27;
UPDATE drink SET category_id =11  where id = 22;

INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (1,1,1);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (1,2,1);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (1,3,1);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (2,1,1);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (2,2,1);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (2,3,5);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (3,11,5);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (3,9,10);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (3,10,10);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (3,1,7);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (4,1,13);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (5,8,12);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (6,9,3);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (6,10,5);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (6,7,5);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (6,4,3);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (6,1,2);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (6,5,3);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (6,3,3);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (7,4,3);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (8,4,3);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (9,4,3);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (10,4,3);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (10,5,3);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (10,9,3);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (11,9,3);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (12,7,5);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (13,7,5);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (14,7,5);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (14,7,1);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (15,9,1);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (16,10,12);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (17,10,12);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (18,7,1);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (18,1,1);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (18,2,1);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (18,3,1);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (18,4,1);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (18,4,5);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (18,4,9);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (18,4,10);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (19,4,10);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (20,4,10);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (21,4,10);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (21,9,12);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (21,10,12);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (21,4,12);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (21,6,12);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (22,7,12);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (23,1,12);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (24,5,12);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (25,6,12);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (26,9,1);
INSERT INTO drink_ingredient (drink_id, ingredient_id, measure_id) VALUES (27,2,1);
