<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>Mindhunters</title>
    <link href="../../css/style.css" rel="stylesheet">

</head>

<body>







<p>First Paragraph</p>
<p>Second Paragraph</p>
<p>Yet one more Paragraph</p>


<div class="list-group  list-element sticky-scroll  ">


    <a  class="list-group-item sidebar-list" id="myID1">
        Ordinary Drink
    </a>


    <a  class="list-group-item sidebar-list" id="myID1">
        Cocktail
    </a>


    <a  class="list-group-item sidebar-list" id="myID1">

        Milk / Float / Shake
    </a>


    <a  class="list-group-item sidebar-list" id="myID1">

        Other/Unknown
    </a>


    <a  class="list-group-item sidebar-list" id="myID1">

        Cocoa
    </a>


    <a  class="list-group-item sidebar-list" id="myID1">

        Shot
    </a>


    <a  class="list-group-item sidebar-list" id="myID1">

        Coffee / Tea
    </a>


    <a  class="list-group-item sidebar-list" id="myID1">

        Homemade Liqueur
    </a>

    <a  class="list-group-item sidebar-list" id="myID1">

        Punch / Party Drink
    </a>


    <a  class="list-group-item sidebar-list" id="myID1">

        Beer
    </a>


    <a  class="list-group-item sidebar-list" id="myID1">

        Soft Drink / Soda
    </a>

</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>

<!-- Bootstrap core JS-->

<!--<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>-->
<!--&lt;!&ndash; Third party plugin JS&ndash;&gt;-->

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
<script src="../../js/BootstrapValidation.js"></script>
<!--&lt;!&ndash;&lt;!&ndash; Core theme JS&ndash;&gt;&ndash;&gt;-->
<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.0.js"></script>

<script src="../../js/receipeList.js"></script>



</body>
</html>
