<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="../../css/style.css" rel="stylesheet">

    <script src="https://kit.fontawesome.com/84fd5d585b.js" crossorigin="anonymous"></script>

    <title>Drink</title>

</head>
<body id="page-top">

<!--Navigation-->
<nav class="navbar navbar-expand-lg" id="mainNav" style="background-color: #1b1e21">
    <div class="container-fluid">
        <a class="navbar-brand " href="#page-top">
            <img src="../../img/logomindhunters.jpg">
        </a>
        <div class="navbar-toggler  text-warning" type="button"
             data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive"
             aria-expanded="false" aria-label="Toggle navigation" style="border-color:#fed136">
            <a> Menu
                <svg class="bi bi-justify" width="1.5em" height="1.4em" viewBox="0 0 16 16" fill="currentColor"
                     xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                          d="M2 12.5a.5.5 0 01.5-.5h11a.5.5 0 010 1h-11a.5.5 0 01-.5-.5zm0-3a.5.5 0 01.5-.5h11a.5.5 0
                          010 1h-11a.5.5 0 01-.5-.5zm0-3a.5.5 0 01.5-.5h11a.5.5 0 010 1h-11a.5.5 0 01-.5-.5zm0-3a.5.5
                          0 01.5-.5h11a.5.5 0 010 1h-11a.5.5 0 01-.5-.5z" clip-rule="evenodd"/>
                </svg>
            </a>
        </div>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav text-uppercase ml-auto">
                <li class="nav-item"><a class="nav-link js-scroll-trigger text-warning" href="#part1 top">Home</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger text-warning" href="#recipePage">Recipe</a>
                </li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger text-warning" href="#bottom-ft">Search</a>
                </li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger text-warning" href="#settingPage">Setting</a>
                </li>
                <div class="btn-group">
                    <button type="button" class="btn dropdown-toggle btn-outline-warning btn-background"
                            data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false">
                        Login
                    </button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <form class="px-4 py-3">
                            <div class="form-group">
                                <label for="exampleDropdownFormEmail1">Email address</label>
                                <input type="email" class="form-control" id="exampleDropdownFormEmail1"
                                       placeholder="email@example.com">
                            </div>
                            <div class="form-group">
                                <label for="exampleDropdownFormPassword1">Password</label>
                                <input type="password" class="form-control" id="exampleDropdownFormPassword1"
                                       placeholder="Password">
                            </div>
                            <div class="form-group">
                                <div class="form-check">
                                    <input type="checkbox" class="form-check-input" id="dropdownCheck">
                                    <label class="form-check-label" for="dropdownCheck">
                                        Remember me
                                    </label>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-outline-warning">Sign in</button>
                        </form>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">New around here? Sign up</a>
                        <a class="dropdown-item" href="#">Forgot password?</a>
                    </div>
                </div>
            </ul>
        </div>
    </div>
</nav>

<!------------------------------------------------------------------------------------------------------->
<section style="background-color: #1b1e21">
    <div class="container" style="color: white">
        <br><br><br>


        <div class="row justify-content-center">
            <div class="col-md-3">
                <h4>Recipe: 'Sex on the beach'</h4>
                <i class="icon-lock" title="Add/delete from favourites">
                    <svg class="bi bi-star-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="orange"
                         xmlns="http://www.w3.org/2000/svg">
                        <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                    </svg>
                </i>
                |
                <i class="icon-lock" title="Delete recipe">
                    <svg class="bi bi-trash" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor"
                         xmlns="http://www.w3.org/2000/svg">
                        <path d="M5.5 5.5A.5.5 0 016 6v6a.5.5 0 01-1 0V6a.5.5 0 01.5-.5zm2.5 0a.5.5 0 01.5.5v6a.5.5 0 01-1 0V6a.5.5 0 01.5-.5zm3 .5a.5.5 0 00-1 0v6a.5.5 0 001 0V6z"/>
                        <path fill-rule="evenodd"
                              d="M14.5 3a1 1 0 01-1 1H13v9a2 2 0 01-2 2H5a2 2 0 01-2-2V4h-.5a1 1 0 01-1-1V2a1 1 0 011-1H6a1 1 0 011-1h2a1 1 0 011 1h3.5a1 1 0 011 1v1zM4.118 4L4 4.059V13a1 1 0 001 1h6a1 1 0 001-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"
                              clip-rule="evenodd"/>
                    </svg>
                </i>
                |
                <i class="icon-lock" title="Edit recipe">
                    <svg class="bi bi-pen" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                              d="M5.707 13.707a1 1 0 01-.39.242l-3 1a1 1 0 01-1.266-1.265l1-3a1 1 0 01.242-.391L10.086 2.5a2 2 0 012.828 0l.586.586a2 2 0 010 2.828l-7.793 7.793zM3 11l7.793-7.793a1 1 0 011.414 0l.586.586a1 1 0 010 1.414L5 13l-3 1 1-3z"
                              clip-rule="evenodd"/>
                        <path fill-rule="evenodd"
                              d="M9.854 2.56a.5.5 0 00-.708 0L5.854 5.855a.5.5 0 01-.708-.708L8.44 1.854a1.5 1.5 0 012.122 0l.293.292a.5.5 0 01-.707.708l-.293-.293z"
                              clip-rule="evenodd"/>
                        <path d="M13.293 1.207a1 1 0 011.414 0l.03.03a1 1 0 01.03 1.383L13.5 4 12 2.5l1.293-1.293z"/>
                    </svg>
                </i>
                <br><br>
                <div>ID number: '17222'</div>
                <div>Category: 'Cocktail'</div>
                <div style="color: red">'Alcoholic'</div>
            </div>
            <div class="col-md-3">
                <img src="https://www.thecocktaildb.com/images/media/drink/2x8thr1504816928.jpg" style="
                        border-radius: 10px;
  padding: 5px; width: 70%;" alt="">
            </div>
        </div>

        <div class="row justify-content-center">
            <div class="col-md-3">
                <br><br><br>
                <div><h5>Ingredients and measure:<br><br></h5></div>
                <div> 'Gin': '1 3/4 shot'</div>
                <div> 'Grand Mariner': '1 Shot'</div>
                <div> 'Lemon Juice': '1/4 Shot'</div>
                <div> 'Grenadine': '1/8 Shot'</div>
            </div>
            <div class="col-md-3">
                <br><br><br>
                <div><h5>Instructions:<br><br></h5></div>
                <div>'Pour all ingredients into a cocktail shaker, mix and serve over ice into a
                    chilled glass.'
                </div>
            </div>
        </div>

        <br><br>
        <div class="row justify-content-center">
            <div class="col">
            </div>
            <div class="col-md-3" style="font-size: 12px">
                <div> Modified: '2017-09-07 21:42:09'</div>
            </div>
            <div class="col">
            </div>
        </div>

    </div>
</section>

<!------------------------------------------------------------------------------------------------------->
<footer>
    <div class="bottom-ft" id="bottom-ft">
        <div class="container container-fluid">
            <div class="row">
                <div class="col-sm-2">
                    <i class="fab fa-github text-warning">Github</i>
                </div>
                <div class="col-sm-2">
                    <i class="fab fa-facebook-square text-warning">facebook</i>
                </div>
                <div class="col-sm-2">
                    <i class="fab fa-twitter-square text-warning">twitter</i>
                </div>
                <div class="col-sm-2">
                    <span class="fab fa-linkedin text-warning">linkedin</span>
                </div>
                <div class="col-sm-2">
                    <span class="fab fa-instagram text-warning">insta</span>
                </div>
                <div class="row">
                    <a class="btn far fa-caret-square-up js-scroll-trigger text-warning" href="#part1 top"></a>2
                </div>
            </div>
            <div class="row-copy">
                <i style="color: white; text-align: center">Copywrite all reserved 2020.</i>
            </div>
        </div>
    </div>
</footer>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
<script src="../../js/BootstrapValidation.js"></script>
<script type="text/javascript" src="../../js/homePage.js"></script>
</body>
</html>